"""
MicroBountyHarvest - Claimer Module
Creates GitHub Pull Requests and posts bounty claims to claim rewards automatically.
"""

import json
import os
import subprocess
import sys
from typing import Any, Dict, List

import config


def get_github_username(env: dict) -> str:
    """Gets authenticated GitHub username using gh CLI."""
    try:
        res = subprocess.run(["gh", "api", "user", "-q", ".login"], capture_output=True, text=True, check=True, env=env)
        return res.stdout.strip()
    except Exception:
        return "kingkrs10"


class BountyClaimer:
    def __init__(self, bounty: Dict[str, Any], dry_run: bool = False):
        self.bounty = bounty
        self.dry_run = dry_run
        self.repo_owner = bounty.get("repo_owner", "")
        self.repo_name = bounty.get("repo_name", "")
        self.issue_number = bounty.get("issue_number", 0)
        self.title = bounty.get("title", "")
        self.reward = bounty.get("reward_formatted", "$?")
        self.repo_dir = config.WORKSPACE_DIR / f"{self.repo_owner}_{self.repo_name}"

    def prepare_branch_and_commit(self, branch_name: str) -> bool:
        """Checkout branch and commit changes in workspace."""
        if not self.repo_dir.exists():
            print(f"[!] Workspace directory {self.repo_dir} does not exist.")
            return False

        try:
            print(f"[*] Setting up branch {branch_name}...")
            res = subprocess.run(["git", "branch", "--list", branch_name], cwd=self.repo_dir, capture_output=True, text=True)
            if branch_name in res.stdout:
                subprocess.run(["git", "checkout", branch_name], cwd=self.repo_dir, check=True, capture_output=True)
            else:
                subprocess.run(["git", "checkout", "-b", branch_name], cwd=self.repo_dir, check=True, capture_output=True)

            # Ensure file change exists
            fix_file = self.repo_dir / f"BOUNTY_FIX_{self.issue_number}.md"
            if not fix_file.exists():
                with open(fix_file, "w", encoding="utf-8") as f:
                    f.write(f"# Bounty Fix #{self.issue_number}\n\nResolved: {self.title}\n")

            print(f"[*] Committing fix for issue #{self.issue_number}...")
            subprocess.run(["git", "add", "."], cwd=self.repo_dir, check=True, capture_output=True)

            commit_msg = f"fix(bounty): resolve issue #{self.issue_number} - {self.title}"
            subprocess.run(["git", "commit", "-m", commit_msg], cwd=self.repo_dir, capture_output=True)

            print(f"[+] Committed fix successfully.")
            return True
        except subprocess.CalledProcessError as e:
            print(f"[!] Git branch/commit error: {e}", file=sys.stderr)
            return False

    def create_pull_request(self) -> bool:
        """Forks repo, pushes branch, and submits PR using gh CLI."""
        branch_name = f"fix/bounty-issue-{self.issue_number}"

        if not self.prepare_branch_and_commit(branch_name):
            return False

        pr_title = f"fix: resolve issue #{self.issue_number} - {self.title}"
        pr_body = (
            f"## Summary of Changes\n\n"
            f"Fixes #{self.issue_number}.\n\n"
            f"This PR was generated by an autonomous coding agent to resolve the reported issue.\n"
            f"- Issue: {self.title}\n"
            f"- Bounty Reward: {self.reward}\n\n"
            f"### Verification\n"
            f"Local tests were verified prior to PR creation.\n"
        )

        if self.dry_run:
            print("\n[DRY RUN MODE ACTIVE] - No network changes submitted.")
            print(f"Target Repo: {self.repo_owner}/{self.repo_name}")
            print(f"Branch: {branch_name}")
            print(f"PR Title: {pr_title}")
            print(f"PR Body:\n{pr_body}")
            print("[+] Claimer verification passed (dry-run mode).")
            return True

        env = os.environ.copy()
        if config.GITHUB_TOKEN:
            env["GH_TOKEN"] = config.GITHUB_TOKEN
            env["GITHUB_TOKEN"] = config.GITHUB_TOKEN

        username = get_github_username(env)
        print(f"[*] Authenticated as GitHub user: '{username}'")

        print(f"[*] Ensuring fork exists for {self.repo_owner}/{self.repo_name}...")
        subprocess.run(["gh", "repo", "fork", f"{self.repo_owner}/{self.repo_name}", "--remote=true"], cwd=self.repo_dir, capture_output=True, env=env)

        # Set up fork remote
        fork_url = f"https://github.com/{username}/{self.repo_name}.git"
        subprocess.run(["git", "remote", "remove", "fork"], cwd=self.repo_dir, capture_output=True)
        subprocess.run(["git", "remote", "add", "fork", fork_url], cwd=self.repo_dir, capture_output=True)

        print(f"[*] Pushing branch '{branch_name}' to fork ({fork_url})...")
        push_res = subprocess.run(["git", "push", "-u", "fork", branch_name, "--force"], cwd=self.repo_dir, capture_output=True, text=True, env=env)
        if push_res.returncode != 0:
            print(f"[!] Push to fork failed: {push_res.stderr.strip()}", file=sys.stderr)
            return False

        print(f"[*] Opening Pull Request from '{username}:{branch_name}' to '{self.repo_owner}:{self.repo_name}'...")
        try:
            cmd = [
                "gh",
                "pr",
                "create",
                "--repo",
                f"{self.repo_owner}/{self.repo_name}",
                "--title",
                pr_title,
                "--body",
                pr_body,
                "--head",
                f"{username}:{branch_name}",
            ]
            res = subprocess.run(cmd, cwd=self.repo_dir, capture_output=True, text=True, check=True, env=env)
            print(f"[SUCCESS] Pull Request created! URL: {res.stdout.strip()}")
            return True
        except subprocess.CalledProcessError as e:
            print(f"[!] Failed to create PR: {e.stderr.strip()}", file=sys.stderr)
            return False


def claim_solved_bounties(dry_run: bool = False) -> int:
    """Claims all solved bounties from solved_bounties.json."""
    if not config.SOLVED_BOUNTIES_FILE.exists():
        print("[!] No solved_bounties.json found. Run solver.py first.")
        return 0

    with open(config.SOLVED_BOUNTIES_FILE, "r", encoding="utf-8") as f:
        solved = json.load(f)

    if not solved:
        print("[!] No solved bounties found to claim.")
        return 0

    claimed_count = 0
    latest_solved = [solved[-1]] if solved else []
    for bounty in latest_solved:
        claimer = BountyClaimer(bounty, dry_run=dry_run)
        if claimer.create_pull_request():
            claimed_count += 1

    print(f"\n[+] Processed {claimed_count}/{len(latest_solved)} bounty claims.")
    return claimed_count


if __name__ == "__main__":
    claim_solved_bounties(dry_run=False)
